### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by XamelionAG** [nalgeon/pokitoki#28]
(env) projektxamelion@xamelion-server:~/pokitoki$ python3 -m bot.bot
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/projektxamelion/pokitoki/bot/bot.py", line 16, in <module>
    from bot import askers
  File "/home/projektxamelion/pokitoki/bot/askers.py", line 15, in <module>
    from bot import ai
  File "/home/projektxamelion/pokitoki/bot/ai/__init__.py", line 1, in <module>
    from . import chatgpt
  File "/home/projektxamelion/pokitoki/bot/ai/chatgpt.py", line 6, in <module>
    from bot.config import config
  File "/home/projektxamelion/pokitoki/bot/config.py", line 143, in <module>
    class ConfigEditor:
  File "/home/projektxamelion/pokitoki/bot/config.py", line 204, in ConfigEditor
    def set_value(self, property: str, value: str) -> tuple[bool, bool]:
TypeError: 'type' object is not subscriptable

//////why it happens?

**Comment by nalgeon** [comment]
The reason is probably the broken config file. Delete it and start from scratch (use [`config.example.yml`](https://github.com/nalgeon/pokitoki/blob/main/config.example.yml) as a starting point).

**Comment by XamelionAG** [comment]
thanks for fast response. i have done a new config.yml by cp and edited it.

result still the same.

**Comment by nalgeon** [comment]
Oh, I get it, thanks. You are using Python 3.8. The bot requires 3.11.

**Comment by XamelionAG** [comment]
it works thank you!

**Comment by nalgeon** [comment]
Sure!
